containerish/openregistry-web

src/routes/__error.svelte, src/routes/__layout.svelte, src/routes/search/index.svelte
=> Fix: Modal on Search page

src/routes/repositories/index.svelte
=> Fix: Repo list for user

src/routes/settings/index.svelte
=> Fix: joined today on settings page

src/routes/__layout.svelte, src/routes/u/[username]/[repo].svelte
=> Fix: Container Pull Command

src/lib/pagination.svelte
=> Fix: pagination active page count

src/app.html
=> Add: plausible analytics api

src/app.html
=> Fix: Plausible Analytics data-api attribute

package.json, src/apis/httpClient.ts, src/app.html, yarn.lock
=> fix: CORS Issue

src/components/overview.svelte, src/lib/footer.svelte, src/routes/repositories/index.svelte
=> Fix: new link for skynet

src/lib/button-outlined.svelte, src/lib/button-solid.svelte
=> Add: solid and outlined buttons

src/lib/card.svelte, src/lib/components/hero.svelte, src/lib/components/sidebar.svelte, src/lib/components/signin.svelte, src/lib/components/signup.svelte, src/lib/footer.svelte, src/lib/icons/email.svelte, src/lib/icons/index.ts, src/routes/(app)/apps/github/connect/+page.svelte, yarn.lock
- Compact design for footer with only necessary links
- Rearranged sidebar options in order of usability, more work is required on this
- Tiles on home page are now anchor tags which will be linked to popular repos once they are uploaded
=> fix: Footer, Sidebar and tiles on home page

package.json, pnpm-lock.yaml, src/lib/icons/check.svelte, src/lib/icons/external-link.svelte, src/lib/icons/git-branch.svelte, src/lib/icons/index.ts, src/lib/icons/recycle.svelte, src/routes/(app)/apps/github/connect/all-deployments/+page.svelte, src/routes/(app)/apps/github/connect/all-deployments/build-compact.svelte, src/routes/(app)/apps/github/connect/all-deployments/build.svelte
Builds page for Github App integration
After successful build process, User will be able to see all of their builds on this page.
The data is only for demonstration purposes. Once the APIs are in place, there will be slight alterations in design along with data
=> add: Design for Builds page of Github app integration

.npmrc, package.json, pnpm-lock.yaml, src/app.d.ts, src/hooks.server.ts, src/lib/schemas/logs-api.ts, src/routes/(app)/apps/github/connect/all-deployments/+page.svelte, src/routes/(app)/apps/github/connect/all-deployments/build-compact.svelte, src/routes/(app)/apps/github/connect/all-deployments/build.svelte, src/routes/(app)/apps/github/connect/all-deployments/settings.svelte, src/routes/(app)/apps/github/connect/setup/+page.server.ts, src/routes/(app)/apps/github/connect/setup/+page.svelte, src/routes/(app)/apps/github/connect/setup/build-project.svelte, src/routes/(app)/apps/github/connect/setup/setup.svelte, src/routes/apis/services/github/actions/logs/+server.ts, svelte.config.js
Design for build settings page, this is a partial commit
We got carried away and ended up integrating APIs for logs streaming on the finish project page.
- Settings page design
- Log stream API for build project page
=> add: Design for Build settings page (partial)

.github/dependabot.yml
We do not have a system to manage our dependencies.
With Dependabot, we will be able to keep our dependencies up to date and dependabot will also call out if there exists a vulnerable dependency in the code
Added dependabot.yml to run weekly
=> add: Dependabot file

src/apis/registry.ts, src/lib/components/sidebar.svelte, src/lib/constants.ts, src/routes/(app)/repositories/+page.svelte, src/routes/(app)/search/+page.svelte, src/routes/(app)/u/+page.svelte, src/routes/(app)/u/[username]/[repo]/+page.svelte, src/routes/apis/registry/list/catalog/+server.ts, src/routes/apis/registry/list/repositories/+server.ts, src/routes/apis/registry/repository-detail/+server.ts
We have been using Axios for API integrations. Since Svelte offers the functionality out of the box. We are resorting to defaults and removing external libraries as much as possible. 
This PR replaces Axios with fetch (+server.ts)
API integration for registries APIs with fetch instead of Axios
=> add: API endpoints for registry backend

src/routes/(app)/+layout.svelte, src/routes/(app)/settings/+page.svelte, src/routes/(app)/u/+page.svelte
Profile and Settings pages needed a little touchup. Also added a delete account in settings page. Functionality(API integration) for which is still pending
_describe the change briefly_
- Profile page touchup
- Settings page, added delete account section
=> fix: Profile and Settings page resizing

src/routes/(app)/apps/github/connect/all-deployments/+page.svelte, src/routes/(app)/apps/github/connect/all-deployments/build.svelte, src/routes/(app)/apps/github/connect/all-deployments/settings.svelte, src/routes/(app)/apps/github/connect/setup/build-project.svelte, src/routes/(app)/apps/github/connect/setup/setup.svelte
We had design in place for github app integration, it wasn't responsive though. We still have to work on api integration however the design is now more responsive to smaller screens and zoom levels
- github app integration flow is now responsive for smaller screens and higher zoom levels
=> fix: Responsiveness of github app integration flow

src/lib/components/high-level-architecture.svelte, src/lib/navbar.svelte, src/routes/(marketing)/+layout.svelte, src/routes/(marketing)/auth/signin/+page.server.ts, src/routes/(marketing)/auth/signin/+page.svelte, src/routes/(marketing)/auth/signup/+page.server.ts, src/routes/(marketing)/auth/signup/+page.svelte
We have introduced separate signup and sign-in pages instead of modals as it makes the flow much cleaner. 
The API integration for these pages was pending since the design PR only included the aesthetics. This PR adds the functionality for all types of signup and sign in flows
- API integration for signup and sign-in pages
=> feat: API integration for Signup Sign-in  pages

src/app.css, src/app.html, src/lib/card.svelte, src/lib/components/hero.svelte, src/lib/components/high-level-architecture.svelte, src/lib/components/how-to-intro.svelte, src/lib/components/index.ts, src/lib/components/loader.svelte, src/lib/components/overview.svelte, src/lib/components/pulse.svelte, src/lib/components/sidebar.svelte, src/lib/footer.svelte, src/lib/navbar.svelte, src/routes/(app)/+layout.svelte, src/routes/(app)/apps/github/connect/+page.svelte, src/routes/(app)/apps/github/connect/all-deployments/+page.svelte, src/routes/(app)/apps/github/connect/all-deployments/build.svelte, src/routes/(app)/apps/github/connect/all-deployments/settings.svelte, src/routes/(app)/apps/github/connect/setup/+page.svelte, src/routes/(app)/apps/github/connect/setup/select-repo.svelte, src/routes/(app)/repositories/+page.svelte, src/routes/(app)/search/+page.svelte, src/routes/(app)/settings/+page.svelte, src/routes/(app)/u/+page.svelte, src/routes/(marketing)/+layout.svelte, src/routes/(marketing)/+page.svelte, src/routes/(marketing)/auth/[slug]/+page.svelte, src/routes/(marketing)/auth/signin/+page.svelte, src/routes/(marketing)/auth/signup/+page.svelte
Our app needs smoother transitions when navigating from components/pages
- This PR adds subtle transitions for the app's internals.
=> feat: Subtle transitions for internals of the app

src/lib/components/hero.svelte, src/lib/components/high-level-architecture.svelte, src/lib/components/overview.svelte, src/lib/components/repo-box.svelte
The animation triggers were messed up maybe they still are, but hey I'm new to gsap. But I think this PR fixes them for 
the overview part. 
- Animation triggers for overview component in homepage feed
=> fix: Animation triggers

src/apis/registry.ts, src/lib/button-outlined.svelte, src/lib/client/openregistry.ts, src/lib/components/logo.svelte, src/lib/components/newRepository.svelte, src/lib/components/repository.svelte, src/lib/formSchemas.ts, src/lib/radioButton.svelte, src/lib/tag.svelte, src/lib/textarea.svelte, src/lib/textfield.svelte, src/lib/types/registry.ts, src/routes/(app)/repositories/+page.server.ts, src/routes/(app)/repositories/+page.svelte, src/routes/(app)/search/+page.server.ts, src/routes/(app)/search/+page.svelte, src/routes/(app)/u/+page.svelte, src/routes/(app)/u/[username]/[repo]/+page.svelte, src/routes/(app)/u/[username]/[repo]/+page.ts, src/routes/(marketing)/auth/signup/+page.svelte
_reason/motivation behind the PR, context of what problem it solves_
_This PR solves the issue #issue_
_describe the change briefly_
=> fix: Repository listing & rendering
